# Generated by Django 4.2.11 on 2024-05-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('year', models.CharField(max_length=256)),
                ('form', models.CharField(max_length=256)),
                ('director', models.CharField(blank=True, max_length=256)),
                ('screenwriter', models.CharField(blank=True, max_length=256)),
                ('producer', models.CharField(blank=True, max_length=256)),
                ('genre', models.CharField(blank=True, max_length=256)),
                ('link', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
